### PR TITLE
Simplified avatar getting

### PR DESCRIPTION
**Pull request by bimoware**

### CODE REVIEW

**Comment by yakasov** [comment]
@bimoware I haven’t checked this repo in like a week or two, my bad - please reopen and I’ll merge, it makes sense

**Comment by bimoware** [comment]
bruh i deleted it thinking this was like 7 years old or something, don't worry about it it's really useless

**Comment by yakasov** [comment]
lmao dw all good, still reopen!! always nice to have more contributions, some of this code needs some improvements - small changes like this add up

**Comment by bimoware** [comment]
Alright lmfao

**Pull request closed without merging**
